python main.py --exp_name simplified_bt --transformer True --langs can,man --n_mono -1 \
	--mono_dataset "can:../../data/Cantonese_Mandarin_chs/mono/train.can.txt.pth,,;man:../../data/Cantonese_Mandarin_chs/mono/train.man.txt.pth,," \
	--para_dataset "can-man:,../../data/Cantonese_Mandarin_chs/para/dev.XX.txt.pth,../../data/Cantonese_Mandarin_chs/para/tst.XX.txt.pth" \
	--mono_directions can,man \
	--pivo_directions can-man-can,man-can-man \
	--pretrained_emb "../../data/Cantonese_Mandarin_chs/train.can.448.vec,../../data/Cantonese_Mandarin_chs/train.man.448.vec" \
	--pretrained_shared_emb "../../data/Cantonese_Mandarin_chs/train.joint.64.vec" \
	--vocab "can:../../data/Cantonese_Mandarin_chs/vocab.joint.txt;man:../../data/Cantonese_Mandarin_chs/vocab.joint.txt" \
	--pretrained_out True \
	--otf_num_processes 8 \
	--otf_sync_params_every 1000 \
	--epoch_size 200000 \
	--batch_size 32 \
	--stopping_criterion "" \
	--lambda_xe_mono 0:1,100000:0.1,300000:0 \
	--lambda_xe_otfd 1 \
	--max_len 32 \
	--n_enc_layers 4 \
	--n_dec_layers 4 \
	--share_enc 4 \
	--share_dec 4 \
	--word_shuffle 2 --word_dropout 0.1 --word_blank 0.2 \
	--share_encdec_emb True \
	--share_decpro_emb True \
	--enc_optimizer adam,lr=0.0001 \
	--dec_optimizer adam,lr=0.0001 \
	--dis_optimizer rmsprop,lr=0.00025 \
	--dropout 0.1 \
	--relu_dropout 0.1 \
	--attention_dropout 0.1 \
	--shared_emb_dim 64 \
	--dump_path "./"

